# run by cmd-> docker-compose -f keyclokmysql_compose.yml up -d
# Creating admin account to-> add user run below command where 9764aeddaacc6b02af44ac767666b826d3a4c76a838d2f95bbd705cbfb2d9b8c is container id
# docker exec 9764aeddaacc6b02af44ac767666b826d3a4c76a838d2f95bbd705cbfb2d9b8c /opt/jboss/keycloak/bin/add-user-keycloak.sh -u admin_user -p admin_password
services:

  mysql-kc:
    image: mysql
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: jboss/keycloak
    ports:
      - 8181:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      #KEYCLOAK_USER: admin_user
      #KEYCLOAK_PASSWORD: admin_password
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      # Same values as the mysql-kc service
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: