server:
  port: 8989

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
  ##GATEWAY CONFIGURATIONS 
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        ## CUSTOMER SERVICE
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            #- StripPrefix=1
        ## PRODUCT SERVICE
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            #- StripPrefix=1
